// create a array of music objects 

const music = [
    {
        id: 1,
        name: "gambler", 
        artist: "kenny rogers",
        album: "the gambler",
        year: 1978,
        genre: "country",
        duration: "3:00" ,
        cover: "" ,
    } ,
    {
        id: 2,
        name: "too Good at Goodbyes",
        artist: "sam smith",
        album: "the thrill of it all",
        year: 2017,
        genre: "pop",
        duration: "3:00" ,
        cover: "" ,
    } ,
    {
        id: 3,
        name: "i'm not the only one",
        artist: "sam smith",
        album: "in the lonely hour",
        year: 2014,
        genre: "pop",
        duration: "3:00" ,
        cover: "",
    } ,
    {
        id: 4,
        name: "hello" ,
        artist: "adele",
        album: "25",
        year: 2015,
        genre: "pop",
        duration: "3:00" ,
        cover: "" ,
    } ,
    {
        id: 5,
        name: "i'm not the only one",
        artist: "sam smith",
        album: "in the lonely hour",
        year: 2014,
        genre: "pop",
        duration: "3:00" ,
        cover: "",
    } ,
    {
        id: 6,
        name: "hello" ,
        artist: "adele",
        album: "25",
        year: 2015,
        genre: "pop",
        duration: "3:00" ,
        cover: "" ,
    } ,
    {
        id: 7,
        name: "i'm not the only one",
        artist: "sam smith",
        album: "in the lonely hour",
        year: 2014,
        genre: "pop",
        duration: "3:00" ,
        cover: "",
    } ,
    {
        id: 8,
        name: "hello" ,
        artist: "adele",
        album: "25",
        year: 2015,
        genre: "pop",
        duration: "3:00" ,
        cover: "" ,
    } ,
    {
        id: 9,
        name: "i'm not the only one",
        artist: "sam smith",
        album: "in the lonely hour",
        year: 2014,
        genre: "pop",
        duration: "3:00" ,
        cover: "",
    } ,
    {
        id: 10,
        name: "hello" ,
        artist: "adele",
        album: "25",
        year: 2015,
        genre: "pop",
        duration: "3:00" ,
        cover: "" ,
    } ,
    {
        id: 11,
        name: "i'm not the only one",
        artist: "sam smith",
        album: "in the lonely hour",
        year: 2014,
        genre: "pop",
        duration: "3:00" ,
        cover: "",
    } ,
    {
        id: 12,
        name: "hello" ,
        artist: "adele",
        album: "25",
        year: 2015,
        genre: "pop",
        duration: "3:00" ,
        cover: "" ,
    } ,
    {
        id: 13,
        name: "i'm not the only one",
        artist: "sam smith",
        album: "in the lonely hour",
        year: 2014,
        genre: "pop",
        duration: "3:00" ,
        cover: "",
    } ,
    {
        id: 14,
        name: "hello" ,
        artist: "adele",
        album: "25",
        year: 2015,
        genre: "pop",
        duration: "3:00" ,
        cover: "" ,
    } ,
    {
        id: 15,
        name: "i'm not the only one",
        artist: "sam smith",
        album: "in the lonely hour",
        year: 2014,
        genre: "pop",
        duration: "3:00" ,
        cover: "",
    } ,
    {
        id: 16,
        name: "hello" ,
        artist: "adele",
        album: "25",
        year: 2015,
        genre: "pop",
        duration: "3:00" ,
        cover: "" ,
    } ,

    // create more at once 
    
]



export default music 